name = "FSRU"
uuid = "3bfc7b26-b1c6-4e53-ac49-fae2428c8b24"
authors = ["Henri Dehaybe <47037088+HenriDeh@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
